# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ff6e626c417ed81724da38e22058e0b700ac4417b853f7034cb27f3d3b7f74f07505a466c1f5598a58ed75dd9e977e2b75d6f1cce4adaaaccbb52099ccb1da5

test:
  secret_key_base: 0b2a6c816ff96a02b07c2e24025c9c52c472b036b384062e852d0b5d9754ff7f9d02ce54c179ec4f46fa209c9e01a978c1fff1b185b7963668830f82a161cc85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
